//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IP.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/IP_WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        IP.ServiceReference1.CompositeType GetDataUsingDataContract(IP.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<IP.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(IP.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLecturer", ReplyAction="http://tempuri.org/IService1/addLecturerResponse")]
        string addLecturer(string nic, string lid, string fname, string lname, string cont_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addLecturer", ReplyAction="http://tempuri.org/IService1/addLecturerResponse")]
        System.Threading.Tasks.Task<string> addLecturerAsync(string nic, string lid, string fname, string lname, string cont_num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewLecturer", ReplyAction="http://tempuri.org/IService1/viewLecturerResponse")]
        System.Data.DataTable viewLecturer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewLecturer", ReplyAction="http://tempuri.org/IService1/viewLecturerResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> viewLecturerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addGrp", ReplyAction="http://tempuri.org/IService1/addGrpResponse")]
        string addGrp(string gid, string no, string eno, string sno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addGrp", ReplyAction="http://tempuri.org/IService1/addGrpResponse")]
        System.Threading.Tasks.Task<string> addGrpAsync(string gid, string no, string eno, string sno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewGroup", ReplyAction="http://tempuri.org/IService1/viewGroupResponse")]
        System.Data.DataTable viewGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewGroup", ReplyAction="http://tempuri.org/IService1/viewGroupResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> viewGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addIns", ReplyAction="http://tempuri.org/IService1/addInsResponse")]
        string addIns(string nic, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addIns", ReplyAction="http://tempuri.org/IService1/addInsResponse")]
        System.Threading.Tasks.Task<string> addInsAsync(string nic, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : IP.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<IP.ServiceReference1.IService1>, IP.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public IP.ServiceReference1.CompositeType GetDataUsingDataContract(IP.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<IP.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(IP.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string addLecturer(string nic, string lid, string fname, string lname, string cont_num) {
            return base.Channel.addLecturer(nic, lid, fname, lname, cont_num);
        }
        
        public System.Threading.Tasks.Task<string> addLecturerAsync(string nic, string lid, string fname, string lname, string cont_num) {
            return base.Channel.addLecturerAsync(nic, lid, fname, lname, cont_num);
        }
        
        public System.Data.DataTable viewLecturer() {
            return base.Channel.viewLecturer();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> viewLecturerAsync() {
            return base.Channel.viewLecturerAsync();
        }
        
        public string addGrp(string gid, string no, string eno, string sno) {
            return base.Channel.addGrp(gid, no, eno, sno);
        }
        
        public System.Threading.Tasks.Task<string> addGrpAsync(string gid, string no, string eno, string sno) {
            return base.Channel.addGrpAsync(gid, no, eno, sno);
        }
        
        public System.Data.DataTable viewGroup() {
            return base.Channel.viewGroup();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> viewGroupAsync() {
            return base.Channel.viewGroupAsync();
        }
        
        public string addIns(string nic, string id) {
            return base.Channel.addIns(nic, id);
        }
        
        public System.Threading.Tasks.Task<string> addInsAsync(string nic, string id) {
            return base.Channel.addInsAsync(nic, id);
        }
    }
}
